# Generated by Django 4.2 on 2023-05-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_playlist_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['-name']},
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='id',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='spotify_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
