# Generated by Django 4.2 on 2023-05-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_playlist_collaborative_playlist_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='snapshot_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
