# Generated by Django 4.2 on 2023-07-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_playlist_snapshot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='number_of_tracks',
            field=models.SmallIntegerField(null=True),
        ),
    ]
