# Generated by Django 4.2 on 2023-07-06 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_playlist_number_of_tracks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='number_of_tracks',
        ),
    ]
