# Generated by Django 4.2 on 2023-07-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_playlist_number_of_tracks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='average_song_length',
            field=models.SmallIntegerField(null=True),
        ),
    ]
