# Generated by Django 5.0.7 on 2024-07-24 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_playlist_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='average_song_length',
            new_name='average_track_length',
        ),
    ]
