# Generated by Django 5.0.7 on 2024-07-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_average_song_length_playlist_average_track_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='number_of_tracks',
            field=models.SmallIntegerField(null=True),
        ),
    ]
