# Generated by Django 5.2.12 on 2026-03-24 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_playlist_number_of_tracks"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "spotify_id",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="playlist",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="playlist",
            name="external_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="playlist",
            name="image_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="playlist",
            name="owner_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="average_track_length",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="number_of_tracks",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="total_duration",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "spotify_id",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("duration_ms", models.IntegerField(default=0)),
                ("external_url", models.URLField(blank=True, default="")),
                (
                    "artists",
                    models.ManyToManyField(related_name="tracks", to="app.artist"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PlaylistTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.IntegerField(default=0)),
                ("added_at", models.DateTimeField(blank=True, null=True)),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlist_tracks",
                        to="app.playlist",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlist_tracks",
                        to="app.track",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "unique_together": {("playlist", "track", "position")},
            },
        ),
    ]
