# Generated by Django 5.2.12 on 2026-03-25 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_artist_playlist_description_playlist_external_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="acousticness",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="danceability",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="energy",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="instrumentalness",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="liveness",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="loudness",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="speechiness",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="tempo",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="valence",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
